"use client";

import { useEffect, useRef, useState } from "react";
import { BookOpen, CalendarDays, ChevronLeft, ChevronRight, Copy, Eye, EyeOff, GripHorizontal, Languages, LayoutGrid, Menu, Plus, RotateCcw, Settings2, X } from "lucide-react";
import { DAYS, DEFINITIONS, DEMO, SHORT_DAYS } from "@/lib/data";
import type { Activity, Category, Definition, Locale, Plan, Store } from "@/lib/types";

const KEY = "sema-planner-v1";
const categories: Category[] = ["Health", "Learning", "Responsibilities", "Life"];
const style: Record<Category, string> = { Health: "activity-health", Learning: "activity-learning", Responsibilities: "activity-responsibilities", Life: "activity-life" };
const copy = {
  en: { planner:"Planner", weeks:"My Weeks", review:"Review", settings:"Settings", add:"Add activity", hideSleep:"Compress sleep", showSleep:"Show full day", shape:"Shape the week, then leave room for life.", local:"Local-first planner\nYour data stays in this browser.", loading:"Loading your week…", open:"Open", full:"Full", overloaded:"Overloaded", selectHint:"Drag across an empty day column to choose a time range", newWeek:"New week", blank:"Blank week", copyWeek:"Copy current week", create:"Create week", cancel:"Cancel", weekName:"Week name", startDate:"Starts", blocks:"blocks", openWeek:"Open week", active:"Active", planned:"Planned", completed:"Completed", remaining:"Still open", plannedTime:"Planned time", busiest:"Busiest day", avg:"Daily average", categories:"Time by category", reflection:"A clear look at how your week is shaped — without an invented score.", language:"Language", display:"Planner display", density:"Grid density", sleepSetting:"Compress sleep hours", sleepHelp:"Removes the shared overnight span from the grid while keeping sleep in calculations.", reset:"Reset demo data", edit:"Edit activity", custom:"New activity", name:"Name", category:"Category", day:"Day", start:"Start", duration:"Duration", save:"Save", remove:"Remove", library:"Activity library", libraryHelp:"Add guidance, then adapt it to your life.", target:"Target", weekly:"Weekly amount", days:"Days", addWeek:"Add to week", newCustom:"Custom activity", drag:"Drag to move · pull the bottom edge to resize", noData:"No planned activities yet." },
  es: { planner:"Planificador", weeks:"Mis semanas", review:"Revisión", settings:"Ajustes", add:"Agregar actividad", hideSleep:"Comprimir sueño", showSleep:"Mostrar día completo", shape:"Dale forma a tu semana y deja espacio para vivir.", local:"Planificador local\nTus datos quedan en este navegador.", loading:"Cargando tu semana…", open:"Libre", full:"Lleno", overloaded:"Sobrecargado", selectHint:"Arrastra sobre una columna vacía para elegir un rango horario", newWeek:"Nueva semana", blank:"Semana vacía", copyWeek:"Copiar semana actual", create:"Crear semana", cancel:"Cancelar", weekName:"Nombre de la semana", startDate:"Comienza", blocks:"bloques", openWeek:"Abrir semana", active:"Activa", planned:"Planificadas", completed:"Completadas", remaining:"Pendientes", plannedTime:"Tiempo planificado", busiest:"Día más cargado", avg:"Promedio diario", categories:"Tiempo por categoría", reflection:"Una mirada clara a tu semana, sin puntajes inventados.", language:"Idioma", display:"Vista del planificador", density:"Densidad de la grilla", sleepSetting:"Comprimir horas de sueño", sleepHelp:"Quita de la grilla el tramo nocturno compartido, pero conserva el sueño en los cálculos.", reset:"Restablecer datos demo", edit:"Editar actividad", custom:"Nueva actividad", name:"Nombre", category:"Categoría", day:"Día", start:"Inicio", duration:"Duración", save:"Guardar", remove:"Eliminar", library:"Biblioteca de actividades", libraryHelp:"Agrega una guía y adáptala a tu vida.", target:"Objetivo", weekly:"Cantidad semanal", days:"Días", addWeek:"Agregar a la semana", newCustom:"Actividad personalizada", drag:"Arrastra para mover · tira del borde inferior para agrandar", noData:"Todavía no hay actividades planificadas." },
};
const names: Record<string, [string,string]> = { Sleep:["Sleep","Sueño"], Exercise:["Exercise","Ejercicio"], Study:["Study","Estudio"], "Deep work":["Deep work","Trabajo profundo"], Admin:["Admin","Administración"], "Friends & family":["Friends & family","Amigos y familia"], "Creative time":["Creative time","Tiempo creativo"] };
const cn = (...v: (string | false | undefined)[]) => v.filter(Boolean).join(" ");
const snap = (n:number) => Math.round(n / 15) * 15;
const clamp = (n:number,min:number,max:number) => Math.max(min,Math.min(max,n));
const fmt = (m:number,locale:Locale) => new Intl.DateTimeFormat(locale === "es" ? "es-AR" : "en-US", { hour:"numeric", minute:"2-digit" }).format(new Date(2026,0,1,Math.floor(m/60)%24,m%60));
const mins = (m:number) => m >= 60 ? `${Math.floor(m/60)}h${m%60 ? ` ${m%60}m` : ""}` : `${m}m`;
const activityName = (name:string,locale:Locale) => names[name]?.[locale === "es" ? 1 : 0] ?? name;
const migrate = (raw:unknown):Store => { const incoming = raw as Partial<Store>; return { ...DEMO, ...incoming, version:2, preferences:{ ...DEMO.preferences, ...incoming.preferences, locale:incoming.preferences?.locale ?? "en" } }; };

function IconButton({label,onClick,children}:{label:string;onClick?:()=>void;children:React.ReactNode}) { return <button type="button" onClick={onClick} aria-label={label} title={label} className="flex size-9 items-center justify-center rounded-md border border-border bg-card text-muted-foreground transition hover:border-primary hover:text-foreground">{children}</button>; }

export function PlannerApp() {
  const [store,setStore] = useState<Store>(DEMO);
  const [ready,setReady] = useState(false);
  const [view,setView] = useState<"Planner"|"My Weeks"|"Review"|"Settings">("Planner");
  const [library,setLibrary] = useState(false);
  const [config,setConfig] = useState<Definition|null>(null);
  const [selectedDays,setSelectedDays] = useState([0,2,4]);
  const [minutes,setMinutes] = useState(300);
  const [mobileDay,setMobileDay] = useState(0);
  const [editing,setEditing] = useState<Activity|null>(null);
  const [navOpen,setNavOpen] = useState(false);
  const [newWeek,setNewWeek] = useState(false);
  const locale = store.preferences.locale;
  const t = copy[locale];
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { try { const raw = localStorage.getItem(KEY); if(raw) setStore(migrate(JSON.parse(raw))); } catch {} setReady(true); },[]);
  useEffect(() => { if(ready) localStorage.setItem(KEY,JSON.stringify(store)); },[ready,store]);
  const plan = store.plans.find(p=>p.id===store.activePlanId) ?? store.plans[0];
  const update = (fn:(s:Store)=>Store) => setStore(fn);
  const updateActivities = (activities:Activity[]) => update(s=>({...s,plans:s.plans.map(p=>p.id===plan.id?{...p,activities}:p)}));
  const saveActivity = (activity:Activity) => updateActivities(plan.activities.some(a=>a.id===activity.id) ? plan.activities.map(a=>a.id===activity.id?activity:a) : [...plan.activities,activity]);
  const openConfig = (d:Definition) => { setConfig(d); setMinutes(d.target); setSelectedDays(d.name==="Sleep"?[0,1,2,3,4,5,6]:[0,2,4]); };
  const addConfigured = () => { if(!config||!selectedDays.length)return; const each=Math.max(15,snap(minutes/selectedDays.length)); const starts=[540,840,1020,600,780,660,960]; updateActivities([...plan.activities,...selectedDays.map((day,i)=>({id:crypto.randomUUID(),name:config.name,category:config.category,day,start:starts[(day+i)%7],duration:each,source:"predefined" as const}))]); setConfig(null); setLibrary(false); };
  const createPlan = (name:string,date:string,mode:"blank"|"copy") => { const id=crypto.randomUUID(); const p:Plan={id,name:name||t.newWeek,weekOf:date||new Date().toLocaleDateString(),activities:mode==="copy"?plan.activities.map(a=>({...a,id:crypto.randomUUID()})):[]}; update(s=>({...s,activePlanId:id,plans:[...s.plans,p]})); setNewWeek(false); setView("Planner"); };
  if(!ready) return <div className="flex h-dvh items-center justify-center text-sm text-muted-foreground">{t.loading}</div>;
  const nav = [["Planner",t.planner,CalendarDays],["My Weeks",t.weeks,LayoutGrid],["Review",t.review,BookOpen],["Settings",t.settings,Settings2]] as const;
  return <main className="flex h-dvh min-h-0 bg-background text-foreground">
    <aside className={cn("w-56 shrink-0 border-r border-border bg-card md:flex md:flex-col",navOpen?"fixed inset-y-0 left-0 z-30 flex flex-col shadow-2xl":"hidden")}>
      <div className="flex h-16 items-center justify-between border-b border-border px-5"><span className="text-xl font-semibold tracking-tight text-primary">sema</span><button className="md:hidden" onClick={()=>setNavOpen(false)} aria-label="Close"><X/></button></div>
      <nav className="flex flex-col gap-1 p-3" aria-label="Main navigation">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setView(id);setNavOpen(false)}} className={cn("flex items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm transition",view===id?"bg-muted text-foreground":"text-muted-foreground hover:bg-muted")}><Icon/>{label}</button>)}</nav>
      <div className="mt-auto whitespace-pre-line p-4 text-xs leading-relaxed text-muted-foreground">{t.local}</div>
    </aside>
    <section className="flex min-w-0 flex-1 flex-col">
      <header className="flex h-16 shrink-0 items-center gap-3 border-b border-border bg-card px-3 md:px-5"><button className="md:hidden" onClick={()=>setNavOpen(true)} aria-label="Menu"><Menu/></button><div className="min-w-0"><p className="truncate text-sm font-semibold">{nav.find(n=>n[0]===view)?.[1]}</p><p className="truncate text-xs text-muted-foreground">{plan.weekOf}</p></div><div className="ml-auto flex items-center gap-2"><IconButton label={locale==="en"?"Español":"English"} onClick={()=>update(s=>({...s,preferences:{...s.preferences,locale:locale==="en"?"es":"en"}}))}><Languages/></IconButton>{view==="Planner"&&<><IconButton label={store.preferences.showSleep?t.hideSleep:t.showSleep} onClick={()=>update(s=>({...s,preferences:{...s.preferences,showSleep:!s.preferences.showSleep}}))}>{store.preferences.showSleep?<EyeOff/>:<Eye/>}</IconButton><button onClick={()=>setLibrary(true)} className="flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground"><Plus/>{t.add}</button></>}</div></header>
      {view==="Planner"&&<PlannerView plan={plan} locale={locale} showSleep={store.preferences.showSleep} density={store.preferences.density} mobileDay={mobileDay} setMobileDay={setMobileDay} save={saveActivity} edit={setEditing} onNewWeek={()=>setNewWeek(true)} t={t}/>} 
      {view==="My Weeks"&&<WeeksView store={store} setStore={setStore} locale={locale} onNew={()=>setNewWeek(true)} t={t}/>} 
      {view==="Review"&&<ReviewView activities={plan.activities} locale={locale} t={t}/>} 
      {view==="Settings"&&<SettingsView store={store} setStore={setStore} t={t}/>} 
    </section>
    {library&&<Library locale={locale} t={t} onClose={()=>setLibrary(false)} openConfig={openConfig} custom={()=>{setLibrary(false);setEditing({id:crypto.randomUUID(),name:"",category:"Life",day:0,start:540,duration:60,source:"custom"})}}/>}
    {config&&<Configure definition={config} locale={locale} t={t} minutes={minutes} setMinutes={setMinutes} days={selectedDays} setDays={setSelectedDays} close={()=>setConfig(null)} add={addConfigured}/>} 
    {editing&&<EditActivity activity={editing} locale={locale} t={t} close={()=>setEditing(null)} save={saveActivity} remove={()=>{updateActivities(plan.activities.filter(a=>a.id!==editing.id));setEditing(null)}}/>}
    {newWeek&&<NewWeekDialog locale={locale} t={t} close={()=>setNewWeek(false)} create={createPlan}/>} 
  </main>;
}

type T = typeof copy.en;
function PlannerView({plan,locale,showSleep,density,mobileDay,setMobileDay,save,edit,onNewWeek,t}:{plan:Plan;locale:Locale;showSleep:boolean;density:Store["preferences"]["density"];mobileDay:number;setMobileDay:(n:number)=>void;save:(a:Activity)=>void;edit:(a:Activity)=>void;onNewWeek:()=>void;t:T}) {
  const hour = density==="compact"?36:density==="detailed"?60:48;
  const range = showSleep ? {start:0,end:1440} : {start:420,end:1380};
  const total = range.end-range.start;
  const gridHeight = total/60*hour;
  const visible = plan.activities.filter(a=>showSleep || a.name!=="Sleep").filter(a=>a.start+a.duration>range.start&&a.start<range.end);
  const dayStats = DAYS.en.map((_,day)=>plan.activities.filter(a=>a.day===day&&a.name!=="Sleep").reduce((n,a)=>n+a.duration,0));
  const [selection,setSelection] = useState<{day:number;anchor:number;current:number}|null>(null);
  const pointerToMinute = (e:React.PointerEvent<HTMLElement>) => { const r=e.currentTarget.getBoundingClientRect(); return clamp(snap(range.start+(e.clientY-r.top)/r.height*total),range.start,range.end); };
  const finishSelection = () => { if(!selection)return; const start=Math.min(selection.anchor,selection.current); const duration=Math.max(15,Math.abs(selection.current-selection.anchor)); if(duration>=15) edit({id:crypto.randomUUID(),name:"",category:"Life",day:selection.day,start,duration,source:"custom"}); setSelection(null); };
  return <div className="flex min-h-0 flex-1 flex-col p-3 md:p-4">
    <div className="mb-3 flex items-center justify-between gap-3"><div><h1 className="text-balance text-lg font-semibold">{plan.name}</h1><p className="text-sm text-muted-foreground">{t.shape}</p></div><button onClick={onNewWeek} className="flex h-9 items-center gap-2 rounded-md border border-border px-3 text-sm font-medium hover:border-primary"><Plus/>{t.newWeek}</button></div>
    <div className="mb-2 flex items-center justify-between md:hidden"><IconButton label="Previous" onClick={()=>setMobileDay((mobileDay+6)%7)}><ChevronLeft/></IconButton><strong className="text-sm">{DAYS[locale][mobileDay]}</strong><IconButton label="Next" onClick={()=>setMobileDay((mobileDay+1)%7)}><ChevronRight/></IconButton></div>
    <div className="mb-2 flex items-center gap-2 text-xs text-muted-foreground"><GripHorizontal/><span>{t.selectHint}</span>{!showSleep&&<span className="ml-auto rounded-full bg-muted px-2 py-1">{locale==="es"?"00:00–07:00 y 23:00–24:00 ocultas":"12–7 AM and 11 PM–12 AM hidden"}</span>}</div>
    <div className="scrollbar min-h-0 flex-1 overflow-auto rounded-lg border border-border bg-card"><div className="relative min-w-[760px] md:min-w-[940px]" style={{height:gridHeight+56}}>
      <div className="sticky top-0 z-20 grid h-14 border-b border-border bg-card" style={{gridTemplateColumns:"62px repeat(7,minmax(96px,1fr))"}}><div/>{DAYS[locale].map((d,i)=><div key={d} className={cn("border-l border-border px-2 py-2",i!==mobileDay&&"max-md:hidden")}><div className="text-xs font-semibold">{SHORT_DAYS[locale][i]}</div><div className="text-[11px] text-muted-foreground">{mins(dayStats[i])} · {dayStats[i]>600?t.overloaded:dayStats[i]>420?t.full:t.open}</div></div>)}</div>
      <div className="absolute inset-x-0 top-14" style={{height:gridHeight}}>
        {Array.from({length:total/60+1},(_,i)=><div key={i} className="absolute inset-x-0 border-t border-border" style={{top:i*hour}}><span className="absolute left-2 -translate-y-1/2 bg-card pr-1 font-mono text-[10px] text-muted-foreground">{fmt(range.start+i*60,locale)}</span></div>)}
        <div className="absolute inset-y-0 left-[62px] right-0 grid grid-cols-7">{DAYS[locale].map((_,day)=><div key={day} className={cn("relative touch-none border-l border-border",day!==mobileDay&&"max-md:hidden")} onPointerDown={e=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);const m=pointerToMinute(e);setSelection({day,anchor:m,current:m})}} onPointerMove={e=>{if(selection?.day===day)setSelection({...selection,current:pointerToMinute(e)})}} onPointerUp={finishSelection}>
          {selection?.day===day&&<div className="pointer-events-none absolute inset-x-1 rounded-md border border-dashed border-primary bg-primary/15" style={{top:(Math.min(selection.anchor,selection.current)-range.start)/60*hour,height:Math.max(12,Math.abs(selection.current-selection.anchor)/60*hour)}}><span className="px-2 text-[10px] text-primary">{fmt(Math.min(selection.anchor,selection.current),locale)} – {fmt(Math.max(selection.anchor,selection.current),locale)}</span></div>}
        </div>)}</div>
        {visible.map(a=><ActivityBlock key={`${a.id}-${a.day}-${a.start}-${a.duration}`} activity={a} locale={locale} range={range} hour={hour} edit={edit} save={save}/>) }
      </div>
    </div></div>
  </div>;
}

function ActivityBlock({activity,locale,range,hour,edit,save}:{activity:Activity;locale:Locale;range:{start:number;end:number};hour:number;edit:(a:Activity)=>void;save:(a:Activity)=>void}) {
  const ref=useRef<HTMLButtonElement>(null);
  const drag=useRef<{x:number;y:number;activity:Activity;mode:"move"|"resize";moved:boolean}|null>(null);
  const [preview,setPreview]=useState(activity);
  const down=(e:React.PointerEvent,mode:"move"|"resize")=>{e.stopPropagation();e.preventDefault();(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,activity:preview,mode,moved:false};};
  const move=(e:React.PointerEvent)=>{if(!drag.current)return;e.stopPropagation();const dy=snap((e.clientY-drag.current.y)/hour*60);const dx=e.clientX-drag.current.x;drag.current.moved ||= Math.abs(dy)>=15||Math.abs(dx)>20;if(drag.current.mode==="resize")setPreview({...drag.current.activity,duration:clamp(drag.current.activity.duration+dy,15,range.end-drag.current.activity.start)});else{const width=ref.current?.parentElement?.parentElement?.clientWidth??700;const dayDelta=Math.round(dx/(width/7));setPreview({...drag.current.activity,day:clamp(drag.current.activity.day+dayDelta,0,6),start:clamp(drag.current.activity.start+dy,range.start,range.end-drag.current.activity.duration)});}};
  const up=(e:React.PointerEvent)=>{if(!drag.current)return;e.stopPropagation();const moved=drag.current.moved;drag.current=null;if(moved)save(preview);else edit(activity);};
  return <button ref={ref} onPointerDown={e=>down(e,"move")} onPointerMove={move} onPointerUp={up} className={cn("group absolute z-10 touch-none overflow-hidden rounded-md border px-2 py-1 text-left shadow-sm transition hover:brightness-110",style[activity.category])} style={{left:`calc(62px + ${preview.day} * ((100% - 62px) / 7) + 4px)`,width:"calc((100% - 62px) / 7 - 8px)",top:(preview.start-range.start)/60*hour,height:Math.max(18,preview.duration/60*hour)}} aria-label={`${activityName(preview.name,locale)}, ${fmt(preview.start,locale)}`}>
    <span className="block truncate text-xs font-semibold">{activityName(preview.name||copy[locale].custom,locale)}</span><span className="block truncate text-[10px] opacity-70">{fmt(preview.start,locale)} · {mins(preview.duration)}</span><span onPointerDown={e=>down(e,"resize")} className="absolute inset-x-0 bottom-0 flex h-3 cursor-ns-resize items-end justify-center opacity-0 group-hover:opacity-100"><span className="mb-0.5 h-0.5 w-7 rounded bg-current"/></span>
  </button>;
}

function Library({locale,t,onClose,openConfig,custom}:{locale:Locale;t:T;onClose:()=>void;openConfig:(d:Definition)=>void;custom:()=>void}) { return <div className="fixed inset-0 z-40 flex justify-end bg-background/70" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="h-full w-full max-w-md overflow-auto border-l border-border bg-card p-5"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">{t.library}</h2><p className="mt-1 text-sm text-muted-foreground">{t.libraryHelp}</p></div><IconButton label="Close" onClick={onClose}><X/></IconButton></div><button onClick={custom} className="mt-5 flex w-full items-center justify-center gap-2 rounded-md border border-dashed border-primary p-3 text-sm text-primary"><Plus/>{t.newCustom}</button>{categories.map(cat=><section key={cat} className="mt-6"><h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{cat}</h3><div className="flex flex-col gap-2">{DEFINITIONS.filter(d=>d.category===cat).map(d=><button key={d.name} onClick={()=>openConfig(d)} className="flex items-center justify-between rounded-lg border border-border p-3 text-left hover:border-primary"><div><span className="text-sm font-medium">{activityName(d.name,locale)}</span><span className="mt-1 block text-xs text-muted-foreground">{t.target} {mins(d.target)}</span></div><ChevronRight/></button>)}</div></section>)}</aside></div>; }

function Configure({definition,locale,t,minutes,setMinutes,days,setDays,close,add}:{definition:Definition;locale:Locale;t:T;minutes:number;setMinutes:(n:number)=>void;days:number[];setDays:(n:number[])=>void;close:()=>void;add:()=>void}) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/75 p-4"><div className="w-full max-w-lg rounded-xl border border-border bg-card p-5 shadow-xl" role="dialog" aria-modal="true"><div className="flex justify-between"><div><p className="text-xs font-semibold text-primary">{definition.guidance}</p><h2 className="mt-1 text-xl font-semibold">{activityName(definition.name,locale)}</h2></div><IconButton label="Close" onClick={close}><X/></IconButton></div><div className="mt-6 flex items-end justify-between"><div><p className="text-sm text-muted-foreground">{t.weekly}</p><p className="text-3xl font-semibold">{mins(minutes)}</p></div></div><input className="mt-4 w-full accent-[var(--primary)]" type="range" min={Math.max(15,definition.min-60)} max={definition.max+120} step="15" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/><fieldset className="mt-6"><legend className="text-sm font-semibold">{t.days}</legend><div className="mt-2 flex flex-wrap gap-2">{SHORT_DAYS[locale].map((d,i)=><button type="button" key={d} aria-pressed={days.includes(i)} onClick={()=>setDays(days.includes(i)?days.filter(x=>x!==i):[...days,i].sort())} className={cn("rounded-md border px-3 py-2 text-xs",days.includes(i)?"border-primary bg-primary text-primary-foreground":"border-border")}>{d}</button>)}</div></fieldset><div className="mt-6 flex justify-end gap-2"><button onClick={close} className="rounded-md border border-border px-4 py-2 text-sm">{t.cancel}</button><button onClick={add} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">{t.addWeek}</button></div></div></div>; }

function EditActivity({activity,locale,t,close,save,remove}:{activity:Activity;locale:Locale;t:T;close:()=>void;save:(a:Activity)=>void;remove:()=>void}) { const [a,setA]=useState(activity); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/75 p-4"><form onSubmit={e=>{e.preventDefault();save({...a,name:a.name||t.custom});close()}} className="w-full max-w-md rounded-xl border border-border bg-card p-5"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">{activity.name?t.edit:t.custom}</h2><p className="mt-1 text-xs text-muted-foreground">{t.drag}</p></div><IconButton label="Close" onClick={close}><X/></IconButton></div><div className="mt-5 flex flex-col gap-4"><label className="text-sm">{t.name}<input autoFocus value={a.name} onChange={e=>setA({...a,name:e.target.value})} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2"/></label><label className="text-sm">{t.category}<select value={a.category} onChange={e=>setA({...a,category:e.target.value as Category})} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2">{categories.map(c=><option key={c}>{c}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">{t.day}<select value={a.day} onChange={e=>setA({...a,day:Number(e.target.value)})} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2">{DAYS[locale].map((d,i)=><option value={i} key={d}>{d}</option>)}</select></label><label className="text-sm">{t.start}<input type="time" step="900" value={`${String(Math.floor(a.start/60)).padStart(2,"0")}:${String(a.start%60).padStart(2,"0")}`} onChange={e=>{const [h,m]=e.target.value.split(":").map(Number);setA({...a,start:h*60+m})}} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2"/></label></div><label className="text-sm">{t.duration}<input type="range" min="15" max="480" step="15" value={a.duration} onChange={e=>setA({...a,duration:Number(e.target.value)})} className="mt-2 w-full accent-[var(--primary)]"/><span className="text-xs text-muted-foreground">{mins(a.duration)} · {fmt(a.start,locale)}–{fmt(a.start+a.duration,locale)}</span></label></div><div className="mt-6 flex justify-between"><button type="button" onClick={remove} className="text-sm text-danger">{t.remove}</button><button className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">{t.save}</button></div></form></div>; }

function NewWeekDialog({locale,t,close,create}:{locale:Locale;t:T;close:()=>void;create:(n:string,d:string,m:"blank"|"copy")=>void}) { const [name,setName]=useState(t.newWeek); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [mode,setMode]=useState<"blank"|"copy">("blank"); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/75 p-4"><form onSubmit={e=>{e.preventDefault();create(name,new Date(`${date}T12:00:00`).toLocaleDateString(locale==="es"?"es-AR":"en-US",{month:"short",day:"numeric",year:"numeric"}),mode)}} className="w-full max-w-md rounded-xl border border-border bg-card p-5"><div className="flex justify-between"><h2 className="text-xl font-semibold">{t.newWeek}</h2><IconButton label="Close" onClick={close}><X/></IconButton></div><div className="mt-5 flex flex-col gap-4"><label className="text-sm">{t.weekName}<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2"/></label><label className="text-sm">{t.startDate}<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2"/></label><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setMode("blank")} className={cn("rounded-md border p-3 text-sm",mode==="blank"?"border-primary bg-primary/10":"border-border")}>{t.blank}</button><button type="button" onClick={()=>setMode("copy")} className={cn("rounded-md border p-3 text-sm",mode==="copy"?"border-primary bg-primary/10":"border-border")}><Copy className="mx-auto mb-1"/>{t.copyWeek}</button></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-md border border-border px-4 py-2 text-sm">{t.cancel}</button><button className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground">{t.create}</button></div></form></div>; }

function WeeksView({store,setStore,locale,onNew,t}:{store:Store;setStore:React.Dispatch<React.SetStateAction<Store>>;locale:Locale;onNew:()=>void;t:T}) { return <div className="overflow-auto p-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">{t.weeks}</h1><p className="mt-1 text-sm text-muted-foreground">{locale==="es"?"Crea, copia y cambia entre tus semanas.":"Create, copy, and switch between your weeks."}</p></div><button onClick={onNew} className="flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground"><Plus/>{t.newWeek}</button></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{store.plans.map(p=><article key={p.id} className={cn("rounded-lg border bg-card p-4",p.id===store.activePlanId?"border-primary":"border-border")}><div className="flex justify-between"><CalendarDays/><span className={cn("rounded-full px-2 py-1 text-xs",p.id===store.activePlanId?"bg-primary text-primary-foreground":"text-muted-foreground")}>{p.id===store.activePlanId?t.active:p.weekOf}</span></div><h2 className="mt-5 font-semibold">{p.name}</h2><p className="mt-1 text-sm text-muted-foreground">{p.activities.length} {t.blocks}</p><button onClick={()=>setStore(s=>({...s,activePlanId:p.id}))} className="mt-4 text-sm font-medium text-primary">{t.openWeek}</button></article>)}</div></div>; }

function ReviewView({activities,locale,t}:{activities:Activity[];locale:Locale;t:T}) { const work=activities.filter(a=>a.name!=="Sleep"); const done=work.filter(a=>a.completed); const total=work.reduce((n,a)=>n+a.duration,0); const byDay=DAYS.en.map((_,d)=>work.filter(a=>a.day===d).reduce((n,a)=>n+a.duration,0)); const busiest=Math.max(...byDay,0); const byCategory=categories.map(c=>({c,m:work.filter(a=>a.category===c).reduce((n,a)=>n+a.duration,0)})).filter(x=>x.m); return <div className="overflow-auto p-6"><h1 className="text-2xl font-semibold">{t.review}</h1><p className="mt-1 text-sm text-muted-foreground">{t.reflection}</p><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label={t.planned} value={String(work.length)}/><Metric label={t.completed} value={`${done.length}/${work.length}`}/><Metric label={t.plannedTime} value={mins(total)}/><Metric label={t.busiest} value={busiest?DAYS[locale][byDay.indexOf(busiest)]:"—"}/><Metric label={t.avg} value={mins(Math.round(total/7))}/></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><section className="rounded-lg border border-border bg-card p-5"><h2 className="font-semibold">{t.categories}</h2><div className="mt-5 flex flex-col gap-4">{byCategory.length?byCategory.map(x=><div key={x.c}><div className="mb-1 flex justify-between text-sm"><span>{x.c}</span><span className="text-muted-foreground">{mins(x.m)}</span></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{width:`${x.m/total*100}%`}}/></div></div>):<p className="text-sm text-muted-foreground">{t.noData}</p>}</div></section><section className="rounded-lg border border-border bg-card p-5"><h2 className="font-semibold">{locale==="es"?"Carga diaria":"Daily load"}</h2><div className="mt-5 flex h-40 items-end gap-2">{byDay.map((m,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t bg-accent" style={{height:`${Math.max(4,m/Math.max(busiest,1)*120)}px`}}/><span className="text-[10px] text-muted-foreground">{SHORT_DAYS[locale][i]}</span></div>)}</div></section></div></div>; }
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-lg border border-border bg-card p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
function SettingsView({store,setStore,t}:{store:Store;setStore:React.Dispatch<React.SetStateAction<Store>>;t:T}) { const setPref=(patch:Partial<Store["preferences"]>)=>setStore(s=>({...s,preferences:{...s.preferences,...patch}})); return <div className="overflow-auto p-6"><h1 className="text-2xl font-semibold">{t.settings}</h1><div className="mt-6 max-w-xl rounded-lg border border-border bg-card p-5"><h2 className="font-semibold">{t.display}</h2><label className="mt-5 block text-sm">{t.language}<select value={store.preferences.locale} onChange={e=>setPref({locale:e.target.value as Locale})} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2"><option value="en">English</option><option value="es">Español</option></select></label><label className="mt-5 block text-sm">{t.density}<select value={store.preferences.density} onChange={e=>setPref({density:e.target.value as Store["preferences"]["density"]})} className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2"><option value="compact">Compact</option><option value="comfortable">Comfortable</option><option value="detailed">Detailed</option></select></label><label className="mt-5 flex items-center justify-between gap-4 text-sm"><span><strong className="block">{t.sleepSetting}</strong><span className="text-muted-foreground">{t.sleepHelp}</span></span><input type="checkbox" checked={!store.preferences.showSleep} onChange={e=>setPref({showSleep:!e.target.checked})} className="size-5 accent-[var(--primary)]"/></label><button onClick={()=>{localStorage.removeItem(KEY);location.reload()}} className="mt-8 flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm"><RotateCcw/>{t.reset}</button></div></div>; }
